module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V2.Duration
import Evergreen.V2.Types
import Evergreen.V3.Duration
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel _ =
    ModelUnchanged


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel _ =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend _ =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg _ =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend _ =
    MsgUnchanged


migrate_Duration_Duration : Evergreen.V2.Duration.Duration -> Evergreen.V3.Duration.Duration
migrate_Duration_Duration old =
    case old of
        Evergreen.V2.Duration.Duration p0 ->
            Evergreen.V3.Duration.Duration p0


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.UrlClicked p0 ->
            Evergreen.V3.Types.UrlClicked p0

        Evergreen.V2.Types.UrlChanged p0 ->
            Evergreen.V3.Types.UrlChanged p0

        Evergreen.V2.Types.NoOpFrontendMsg ->
            Evergreen.V3.Types.NoOpFrontendMsg

        Evergreen.V2.Types.DidCheckPlayer p0 p1 ->
            Evergreen.V3.Types.DidCheckPlayer p0 p1

        Evergreen.V2.Types.DidInputTime p0 ->
            Evergreen.V3.Types.DidInputTime p0

        Evergreen.V2.Types.ClickedAddRecord ->
            Evergreen.V3.Types.ClickedAddRecord

        Evergreen.V2.Types.GotNow p0 p1 ->
            Evergreen.V3.Types.GotNow (p0 |> migrate_Duration_Duration) p1

        Evergreen.V2.Types.ClickedDelete p0 ->
            Evergreen.V3.Types.ClickedDelete p0
